language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - pyhton manage.py migrate && docker-compose run app sh -c "python manage.py test && flake8"
